export const mediaTypes = {
    IMAGE: 'image',
    VIDEO: 'video',
    AUDIO: 'audio',
    DOCUMENT: 'document',
    EVERYONE: "Everyone",
    NOTIFICATION: "notification",
    FOLLOWERS: 'Followers',
};

export const NotificationTypes = {
    //---FOLLOW TO ANOTHER USERS----------//
    CAR_LISTING_NOTIFICATION: 1,
    COMMENTS_NOTIFICATION: 2,
    LIKES_NOTIFICATION: 3,
    SEND_MESSAGE_NOTIFICATION:4
};
export const variableTypes = {
    NO_PURCHASES_FOUND_FOR_PLAN: "No purchases found for plan",
    USER_PLAN_NOT_FOUND: "User plan not found",
    COULD_NOT_GEOCODE_ADDRESS: "Could not geocode this address",
    LOCATION_REQUIRED: "Location string is required",
    MAIN_PLAN_PURCHASE_NOT_FOUND: "Main plan purchase not found.",
    NO_PURCHASES_FOUND_FOR_ACTIVE_PLAN: "No purchases found for the active plan.",
    NO_ACTIVE_PLAN_FOUND: "No active plan found.",
    SELLER_SLOT_DETAILS_FETCHED_SUCCESSFULLY: "Seller slot details fetched successfully",
    PDF_GENERATION_FAILED: "PDF generation failed",
    CAR_DETAILS_RETRIEVED_SUCCESSFULLY: "Car details retrieved successfully",
    SOMETHING_WENT_WRONG: "Something went wrong",
    SLOT_REQUEST_NOT_FOUND: "Slot request not found",
    VIN_AND_MILEAGE_REQUIRED: "VIN and mileage are required",
    BRAND_MODEL_YEAR_REQUIRED: "Brand, model, and year are required",
    BRAND_REQUIRED: "Brand is required",
    SEARCH_FAILED: "Search failed",
    FAILED_TO_FETCH_VEHICLE_DETAILS: "Failed to fetch vehicle details",
    FAILED_TO_FETCH_VEHICLE_BY_VIN: "Failed to fetch vehicle by VIN",
    FAILED_TO_FETCH_MODELS: "Failed to fetch models",
    FAILED_TO_FETCH_BRANDS: "Failed to fetch brands",
    EUROTAX_API_FAILED: "Eurotax API call failed",
    INVALID_LAST_MFK_DATE: "Invalid last MFK date.",
    MFK_TITLE: "MFK Status",
    FAILED_TO_ADD_PURCHASE_AGREEMENT: "Failed to add purchase agreement.",
    PURCHASE_AGREEMENT_ADDED_SUCCESS: "Purchase agreement added successfully.",
    REEL_REMOVED_SUCCESSFULLY: "Reel removed successfully.",
    SAVED_REEL_NOT_FOUND: "Saved reel not found.",
    EMAIL_AND_PASSWORD_REQUIRED: "Email and password are required.",
    MAKE_AND_MODEL_REQUIRED: "Make and model are required.",
    BRAND_ID_REQUIRED: "Brand ID is required.",
    CAR_ID_REQUIRED: "Car ID is required.",
    FILE_UPLOADED_SUCCESSFULLY: "File uploaded successfully.",
    FILE_REQUIRED: "File is required.",
    SUCCESS: "Success.",
    DATA_ADDED_SUCCESSFULLY: "Data added successfully.",
    DATA_UPDATED_SUCCESSFULLY: "Data updated successfully.",
    DATA_DELETED_SUCCESSFULLY: "Data deleted successfully.",
    DATA_FOUND_SUCCESSFULLY: "Data found successfully.",
    NOTIFICATION: "notification",
    GIVEAWAYANNOUCMENT: "giveAwayAnnoucment",
    ON: 'On',
    OFF: 'Off',
    BEARER: 'Bearer',
    AUTHORIZATION: 'authorization',

    ALLREADY_HAVE_ACCOUNT: 'allreadyHaveAccount',
    FALIED_TO_USERS_CREATE: 'failedToUsersCreate',
    INTERNAL_SERVER_ERROR: 'internalServerError',
    INVALID_OTP: 'invalidOtp',
    OTP_VERIFIED: 'otpVerified',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    ACCOUNT_NOT_FOUND: 'accountNotFound',
    EMAIL_NOT_FOUND: 'emailNotFound',
    PASSWORD_CHANGED: 'passwordChanged',
    PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH: 'passwordAndConfirmPasswordNotMatch',
    PROFILE_UPDATED_SUCCESSFULLY: 'profileUpdatedSuccessfully',
    USER_DETAILED_FOUND_SUCCESSFULLY: 'userDetailedFoundSuccessfully',
    ACCOUNT_VERIFIED_CODE_SENT: 'accountVerifiedCodeSent',
    PASSWORD_NOT_CHANGED: 'passwordNotChanged',
    PASSWORD_DO_NOT_MATCH: 'passwordsDoNotMatch',
    DATA_NOT_FOUND: 'dataNotFound',
    CURRENT_PASSWORD_INCORRECT: 'currentPasswordIncorrect',
    INVALID_OR_MISSING_TOKEN: "INVALID_OR_MISSING_TOKEN",
    INVALID_TOKEN: "INVALID_TOKEN",
    NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
    ACCOUNT_ACTIVATE: "accountActivate",
    ERROR_SENDING_TO_EMAIL: "errorToSendingEmail",
    VERIFY_YOUR_ACCOUNT: "verifyYourAccount",
    USER_MODE_UPDATED_SUCCESSFULLY: "Usermodeupdatedsuccessfully.",
    LANGUAGE_UPDATED_SUCCESSFULLY: "languageUpdatedSuccessfully",
    NOTIFICATION_STATUS_UPDATED_SUCCESSFULLY: "notificationStatusUpdatedSuccessfully",
    CAR_ALREADY_WISHLISTED: "carAlreadyinWishlist",
    CAR_ADDED_WISHLIST: "CarAddedtoWishlist",
    INVALID_LANGUAGE_CODE: "InvalidLanguageCode",
    INVALID_VALUE_FOR_NOTIFICATION_STATUS: "InvalidValueForNotificationStatus",
    ALL_CARS_FETCHED_SUCCESSFULLY: "AllCarsFetchedSuccessfully.",
    CAR_DETAILS_FETCHED_SUCCESSFULLY: 'CarDetailsFetchedSuccessfully',
    SWITCH_TO_SELLER_MESSAGE: "switchToSellerMessage",
    SWITCH_TO_BUYER_MESSAGE: "switchToBuyerMessage",
    SUCESSFULLY_SWITCH_AS_SELLER_MODE: "accountSwitchedToSeller",
    SUCESSFULLY_SWITCH_AS_BUYER_MODE: "accountSwitchedToBuyer",
    ALLREADY_HAVE_ACCOUNT_AS_BUYER: "alreadyRegisteredAsBuyer",
    ALLREADY_HAVE_ACCOUNT_AS_SELLER: "alreadyRegisteredAsSeller",
    CAR_CREATED_SUCCESSFULLY: "carCreatedSuccessfully",
    CAR_LISTED_SUCCESSFULLY: "carListedSuccessfully",
    USER_UPDATED_PERSONAL_SELLER_SUCCESSFULLY: "userUpdatedToPersonalSellerSuccessfully",
    USER_UPDATED_BUSINESS_SELLER_SUCCESSFULLY: "userUpdatedToBusinessSellerSuccessfully",
    ALRAEDY_SELLER_JUST_SWITCH_ROLE: "alreadySellerJustSwitchRole",
    NOTIFICATION_CAR_SUCCESFULLY_LISTED: "carSuccessfullyListedToSendNotification",
    USERS_BUYER_NOT_FOUND: "usersBuyerNotFound",
    NO_NOTIFICATION_YET: "noNotificationsYet",
    NOTIFICATION_LIST_FOUND_SUCCESFULLY: "notificationListFound",
    LOGIN_SUCCESSFULLY: "login Successfully",
    ADMIN_DETAILED_FOUND_SUCCESSFULLY: 'admin Detailed Found Successfully',
    ACCOUNT_SUCCESSFULLY_CREATED: "accountSuccessfullyCreated",
    CAR_ADDED_TO_WISHLIST: "carAddedToWishList",
    FAILED_TO_CAR_LIST: "failedToCarList",
    NO_WISHLIST_FOUND: "noWishlistFound",
    WISH_LIST_FOUND: "wishListFound",
    REMOVE_CAR_FROM_WISHLIST: "removedCarFromWishlist",
    CAR_ALLREDY_IN_YOUR_WISHLIST: "allredyInYourWishlist",
    ACCOUNT_VERIFICATION: "accountVerification",
    FORGOT_PASSWORD_OTP_SUBJECT: "forgotPasswordOtpSubject",
    LOGIN_SUCCESSFULLY: "loginSuccessfully",
    ADMIN_DETAILED_FOUND_SUCCESSFULLY: 'adminDetailedFoundSuccessfully',
    PASSWORD_RESET_FAILED: 'passwordResetFailed',
    PASSWORD_RESET_SUCCESSFULLY: 'passwordResetSuccessfully',
    PASSWORD_CAN_NOT_SAME: 'passwordCanNotSame',
    PASSWORD_LINK_IS_SENT: 'passwordLinkIsSent',
    ADMIN_NOT_FOUND: 'adminNotFound',
    BUYER_FETCHED_SUCCESSFULLY: "buyerFetchedSuccessfully",
    BUYER_NOT_FOUND: "buyerNotFound",
    SELLER_NOT_FOUND: "sellerNotFound",
    SELLER_FETCHED_SUCCESSFULLY: "sellerFetchedSuccessfully",
    ROLE_NOT_FOUND: "roleNotFoundForThisUser",
    USER_ID_ROLE_AND_ISBLOCKED_REQUIRED: "user_idRoleAndIsBlockedAreRequired",
    ONLY_0_AND_1_ALLOWED: "onlyZeroOrOneAllowedForIsBlocked",
    USER_BLOCKED_BY_ADMIN: "YourAccountHasBeenBlockedByTheAdminPleaseContactSupportForFurtherAssistance",
    CAR_NOT_FOUND: "Car not found.",
    DASHBOARD_DATA_FETCHED_SUCCESSFULLY: "Data fetched successfully.",
    ALL_NOTIFICATION_CLEARD: "allNotificationsCleared",
    REEL_SAVED_SUCCESSFULLY: "reelSavedSuccessfully",
    CAR_REMOVED_SUCCESSFULLY: "carRemovedFromSavedReel",
    SLOT_LIMIT_EXCEEDED: "Slot limit exceeded.",
    DATA_FETCHED_SUCCESSFULLY: "Data fetched successfully.",

    
    CAR_UPDATED_SUCCESSFULLY: "carUpdatedSuccessfully",
    CAR_DELETED_SUCCESSFULLY: "carDeletedSuccessfully",
    CAR_NOT_FOUND_OR_UNAUTHORIZED: "carNotFoundOrUnauthorized",
    UPDATE_FAILED: "updateFailed",
    DELETE_FAILED: "deleteFailed",
    PLAN_NOT_FOUND: "Plan Not Found",
    CAR_SWAPPED_SUCCESSFULLY: "Car swapped successfully.",
    BASIC_PLAN_ALREADY_USED: "Basic Plan Already Used",
    PLAN_PURCHASED_SUCCESSFULLY: "Plan Purchased Successfully",

    SLOT_REQUEST_SENT_SUCCESSFULLY: 'SLOT_REQUEST_SENT_SUCCESSFULLY',
    INVALID_REQUESTED_SLOTS: 'INVALID_REQUESTED_SLOTS',
    IMAGE_URL_REQUIRED: "Image URL is required.",
    IMAGE_NOT_FOUND: "Image not found.",
    IMAGE_DELETED_SUCCESSFULLY: "Image deleted successfully.",
    MISSING_PRICE_OR_PLANTYPE: 'MISSING_PRICE_OR_PLANTYPE',

    // ─── STEP 1: New account type keys ───────────────────────────────────────
    COMPANY_REGISTRATION_PENDING: "companyRegistrationPending",
    COMPANY_ACTIVATED_SUCCESSFULLY: "companyActivatedSuccessfully",
    COMPANY_ALREADY_ACTIVATED: "companyAlreadyActivated",
    COMPANY_NOT_FOUND: "companyNotFound",
    INVALID_ACCOUNT_TYPE: "invalidAccountType",
    ACCOUNT_UNDER_REVIEW: "accountUnderReview",
    VIN_NUMBER_REQUIRED: "vinNumberRequired",
    TYPE_APPROVAL_REQUIRED: "typeApprovalRequired",
    NO_VEHICLE_FOUND_FOR_VIN_NUMBER: "noVehicleFoundForVinNumber",
    NO_VEHICLE_FOUND_FOR_TYPE_APPROVAL_NUMBER: "noVehicleFoundForTypeApprovalNumber",
    VEHICLE_FETCHED_SUCCESSFULLY: "vehicleFetchedSuccessfully",

    NOT_ALLOWED_TO_LIST_CARS:"notAllowedToListCars",
    INVALID_LAST_MFK_DATE :"INVALID LAST MFK DATE",
    LAST_MFK_DATE_CANNOT_BE_IN_FUTURE: "Last MFK date cannot be in the future.",
    LAST_MFK_DATE_CANNOT_BE_EARLIER_THAN_FIRST_REGISTRATION_DATE: "Last MFK date cannot be earlier than first registration date.",
    FIRST_REGISTRATION_DATE_CANNOT_BE_IN_FUTURE: "First registration date cannot be in the future.",
        Inquiry_sent_successfully:"Inquirysentsuccessfully",
    Physical_visit_request_submitted_successfully:"Physicalvisitrequestsubmittedsuccessfully"

};

export const StatusCode = {
    status200: 200,
    status201: 201,
    status202: 202,
    status204: 204,
    status208: 208,
    status304: 304,
    status400: 400,
    status401: 401,
    status402: 402,
    status403: 403,
    status404: 404,
    status405: 405,
    status406: 406,
    status413: 413,
    status500: 500,
    status507: 507,
};

export const emailVerificationTranslations = {
    en: {
        verify_account: "Verify Your Account",
        confirm_email: "Confirm Your Email Address",
        enter_code_instruction: "Enter the code below in our App to confirm your email address. If you didn't create an account with us, you can safely ignore this email.",
        cheers: "Cheers,",
        team_name: "Car Zone Team",
        need_help: "Need More Help?",
        help_link: "We are here to help you out",
    },
    fr: {
        verify_account: "Vérifiez votre compte",
        confirm_email: "Confirmez votre adresse e-mail",
        enter_code_instruction: "Saisissez le code ci-dessous dans notre application pour confirmer votre adresse e-mail. Si vous n'avez pas créé de compte chez nous, vous pouvez ignorer cet e-mail.",
        cheers: "Cordialement,",
        team_name: "L'équipe Car Zone",
        need_help: "Besoin d'aide ?",
        help_link: "Nous sommes là pour vous aider",
    },
    de: {
        verify_account: "Bestätigen Sie Ihr Konto",
        confirm_email: "Bestätigen Sie Ihre E-Mail-Adresse",
        enter_code_instruction: "Geben Sie den untenstehenden Code in unsere App ein, um Ihre E-Mail-Adresse zu bestätigen. Wenn Sie kein Konto bei uns erstellt haben, können Sie diese E-Mail ignorieren.",
        cheers: "Viele Grüße,",
        team_name: "Car Zone Team",
        need_help: "Brauchen Sie mehr Hilfe?",
        help_link: "Wir sind hier, um Ihnen zu helfen",
    },
    it: {
        verify_account: "Verifica il tuo account",
        confirm_email: "Conferma il tuo indirizzo email",
        enter_code_instruction: "Inserisci il codice qui sotto nella nostra app per confermare il tuo indirizzo email. Se non hai creato un account con noi, puoi ignorare questa email.",
        cheers: "Cordiali saluti,",
        team_name: "Il team di Car Zone",
        need_help: "Hai bisogno di aiuto?",
        help_link: "Siamo qui per aiutarti",
    },
};

export const forgotPasswordTranslations = {
    en: {
        forgot_your_password: "Forgot Your Password?",
        we_recived: "We received a request to reset your password. Please use the OTP below to proceed:",
        password_reset: "If you didn’t request a password reset, you can safely ignore this email.",
        cheers: "Cheers,",
        team_name: "Car Zone Team",
        need_help: "Need More Help?",
        help_link: "We are here to help you out",
    },
    fr: {
        forgot_your_password: "Mot de passe oublié ?",
        we_recived: "Nous avons reçu une demande de réinitialisation de votre mot de passe. Veuillez utiliser le code OTP ci-dessous pour continuer :",
        password_reset: "Si vous n'avez pas demandé de réinitialisation de mot de passe, vous pouvez ignorer cet e-mail en toute sécurité.",
        cheers: "Cordialement,",
        team_name: "Équipe Car Zone",
        need_help: "Besoin d'aide ?",
        help_link: "Nous sommes là pour vous aider",
    },
    de: {
        forgot_your_password: "Passwort vergessen?",
        we_recived: "Wir haben eine Anfrage zum Zurücksetzen Ihres Passworts erhalten. Bitte verwenden Sie den folgenden OTP-Code, um fortzufahren:",
        password_reset: "Wenn Sie kein Zurücksetzen des Passworts angefordert haben, können Sie diese E-Mail sicher ignorieren.",
        cheers: "Viele Grüße,",
        team_name: "Car Zone Team",
        need_help: "Brauchen Sie Hilfe?",
        help_link: "Wir sind hier, um Ihnen zu helfen",
    },
    it: {
        forgot_your_password: "Hai dimenticato la password?",
        we_recived: "Abbiamo ricevuto una richiesta per reimpostare la tua password. Usa l'OTP qui sotto per procedere:",
        password_reset: "Se non hai richiesto una reimpostazione della password, puoi ignorare tranquillamente questa email.",
        cheers: "Saluti,",
        team_name: "Team Car Zone",
        need_help: "Hai bisogno di aiuto?",
        help_link: "Siamo qui per aiutarti",
    },
};